# 1. STRUKTUR DATA PYTHON


# 1. List

in python, a list is the main data structur use to store a mutable sequence of elements. The sequence of data elements stored in the list not be of the same type.

to crate a list, the data elements need to be enclosed in [] and they need to be separated by a comma. For example, the following code creates four data elements together which are of different type.

In [1]:
aList = ["John", 33, "Toronto", True]

In [2]:
aList

['John', 33, 'Toronto', True]

In [3]:
type(aList)

list

In [4]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]

In [5]:
bin_colors

['Red', 'Green', 'Blue', 'Yellow']

# 2. Tuples

The second data structure that can be used to store of collection is tuple. In constrast to list, tuples are immuteable(read only) data structures. Tuples consist of several elements surrounded by ().

like lists, elements within a tuple can be of different types. They also allow complex data types for their elements. So there can be a tuple within a tuple providing a way to create nested data structure. Capability to create nested data structure os especially usefull in iterative and recursive alghoritm .

Follow code demonstrate how to create tuples

In [7]:
binColor = ('Red', 'Grean', 'Blue', 'Yellow')
print(f"The second elements of the tuples is {binColor[1]}")
print(f"The after third elements onward are  {binColor[2:]}")

The second elements of the tuples is Grean
The after third elements onward are  ('Blue', 'Yellow')


Let us define nested tuple data structure 

In [9]:
nestedTuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nestedTuple[2])}")

The maximum value of the inner tuple 300


# 3. Dictionary
To create a simple dictionary that assign colors to varius variables, the key-value pairs need to be enclosedin {}. For example, the following code to creates a simple dictionary consisting of three key-value pairs.

In [10]:
binColors = {
    "manualColor": "Yellow",
    "approvedColor": "Green",
    "refusedColor": "Red"
}

print(binColors)

{'manualColor': 'Yellow', 'approvedColor': 'Green', 'refusedColor': 'Red'}


In [11]:
binColors.get('approvedColor')

'Green'

In [12]:
binColors['approvedColor']

'Green'

In [13]:
binColors['approvedColor'] = "Purple"

print(binColors)

# 4. Sets
A sets is defined as a collection of elements which can be pf different types. The elements are enclosed with {}. For example, have a look at the following code block:

In [15]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [16]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'leaves', 'blood', 'rose', 'dandelions', 'fire hydrant'}


In [17]:
print(f"The interaction of yellow and red is {yellow&red}")

The interaction of yellow and red is {'leaves', 'fire hydrant'}


# 5. Data Frames
Data frames is a data structure used to store tabular data available in Python's pandas package. It is one of the most important data structures for alghorithm and is used to precess traditional structured data.
Now let us represent this by a Data Frames

A simple DataFrames can be created by using the following code:

In [21]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]
])

df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


# 1.4.1 Column Selection
The values of name and age columns are

In [22]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

the positioning of a column is deterministic in a data frame. Fourth column can be retrieved by its position as follows:

In [24]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

# 1.4.2 Row Selection
Each row in DataFrame corresponds to a data-point in our problem space. We need to perform row selection if we want to create a subset of the data elements we have in our problem space. This subset can be create by using one of the two methods.

By specifying their positioning By specifying a filter A subset of rows can be retrieved by its position as follows:

In [25]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

To create a subset by specifying the filter we need to use one or more columns to define the selection criterion. For example,a subset of data elements can be selected by this methods as follows:

In [26]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

# 6. Matrix
A matrix is a two-dimensional data structure with a fixed number of columns and rows. Each elements of a matrix can be reffered to by its columns and the row.

In [27]:
import numpy as np
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [28]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [30]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# 2. Tipe Data Abstrak
# 1. Vector 
A vector is a single dimension structure to store data. First, use list, second, use array

In [31]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [32]:
print(type(myVector))

<class 'list'>


In [33]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [34]:
print(type(myVector))

<class 'numpy.ndarray'>


# 2. Stack

Stack is a linier data structure to store one dimensional list. Its can store items either in Last-in Firts-out (LIFO) manner. The defining characteristic of a stack is way elements are added and removed from it. A new elements is added at one end and an elements is removed from that end only.

Following are the operations related to stack:

isEmpty: Returns true if stack is empty, push: Adds a new element. pop: it returns the elements added most recently and removes it.
let us create a class named stack in python, where we will define all the operations relatedto stack class. The code of this class will be as following:

In [35]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

to push four elements to the stack following code can be used:

# Populate the stack

In [36]:
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

# POP

In [37]:
stack.pop()

'Yellow'

In [38]:
stack.isEmpty()

False

In [42]:
color = ['Red']

In [ ]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

# 3. Queue
Like stack queue stores n elements in a single-dimensonal structure. The elements are added and removed in First-in First-out (FIFO)format. One end of the queue is called rear and the other one is called the front. The elements are romoved from the front, and the operation is called dequeue. The elements are added at the rear and the operation is called enqueue.
the queue shown in the precending figure can be implemented by using the following code:

In [46]:
class Queue(object):
    def __init__(self):
        self.items= []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [47]:
queue = Queue()

In [48]:
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [49]:
print(queue.dequeue())

Red
